pull_request_rules:
- name: automatic merge for main when CI passes and 2 reviews
  conditions:
  - check-success=CI PIPELINE / operator (pull_request)
  - base=main
  actions:
    merge:
      method: merge
