name: CI PIPELINE

on:
  pull_request:
    branches: ["main"]

jobs:
  operator:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Call make test
        run: ls
